title: Spring 2023 - Mobile Application Development
description: Lectures and Example code for Spring 2023 - Mobile Application Development Course by Dr. Hasan Ali Khattak - SEECS NUST Pakistan.
remote_theme: pages-themes/leap-day@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
