// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSiWacopzlUMrmFu7cUV-K_SFvl-2aOI',
    appId: '1:697057775908:web:591967d1cb8917eb8c23b1',
    messagingSenderId: '697057775908',
    projectId: 'mad101-740b8',
    authDomain: 'mad101-740b8.firebaseapp.com',
    storageBucket: 'mad101-740b8.appspot.com',
    measurementId: 'G-427FN97F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzcDsi4ENgnB3t19e4gBS-eaHJuvZN9s',
    appId: '1:697057775908:android:1c3fdde2799df1978c23b1',
    messagingSenderId: '697057775908',
    projectId: 'mad101-740b8',
    storageBucket: 'mad101-740b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVehhzq4YOaVOYDQ56YBbsz1CByHGm-Q',
    appId: '1:697057775908:ios:fbda607b9c1e08018c23b1',
    messagingSenderId: '697057775908',
    projectId: 'mad101-740b8',
    storageBucket: 'mad101-740b8.appspot.com',
    iosClientId: '697057775908-lqib2dr1s8molqfgt2tbccc98rdt7t5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.p7Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVehhzq4YOaVOYDQ56YBbsz1CByHGm-Q',
    appId: '1:697057775908:ios:fbda607b9c1e08018c23b1',
    messagingSenderId: '697057775908',
    projectId: 'mad101-740b8',
    storageBucket: 'mad101-740b8.appspot.com',
    iosClientId: '697057775908-lqib2dr1s8molqfgt2tbccc98rdt7t5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.p7Firebase',
  );
}
